spring:
  application:
    name: springRESTAPI
  datasource:
    url: jdbc:h2:./appdb
    username: sa

  h2:
    console:
      enabled: true

  jpa:
    generate-ddl: true

# dd-auto: create -> it will always drop table if exists and create a new one at Spring startup (DDL).
# if we want to retain the table then use option :validate
    hibernate:
      ddl-auto: validate

    show-sql: true


server:
  port: 8083

